[build]
  command = "npm run build"
  publish = "dist" # o "build", depende del framework

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173 # si usas Vite

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
